// src/main.js
import './js/header.js';
import './js/theme-dark-mode.js';
import './js/hero.js';
import './js/all-category.js';
import './js/popular-recipes.js'; 
import './js/recipe-cards.js';
import './js/popular-recipes.js';
import './js/filters.js';
import './js/favorites.js';